apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: redis
    tier: db
  ports:
  - protocol: TCP
    port: 6379 # service port
    targetPort: 6379 # container port